version: '3.8'

services:
  # Node.js Express App
  ai-node-service:
    build:
      context: .
    env_file:
      - .env
    container_name: ai-node-service
    ports:
      - "3000:3000"
    command: ["sh", "-c", "sleep 10 && npm start"]
    networks:
      - hn_network

networks:
  hn_network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"